### PR TITLE
[WIP] Use UBI8 as base image

### PR DESCRIPTION
**Pull request by leifmadsen**

### CODE REVIEW

**Comment by leifmadsen** [comment]
Not currently working due to missing dependencies, but wanted to push this so it wasn't just sitting locally on my computer.

**Comment by leifmadsen** [comment]
@mrunge any suggestions on getting all the dependencies from somewhere so we can build on UBI8?

**Comment by mrunge** [comment]
We can put missing deps into centos opstools. Q: what is missing?

**Comment by leifmadsen** [comment]
> We can put missing deps into centos opstools. Q: what is missing?

Cool, Wasn't sure if there was maybe another repo I could enable. It seems to be `python3-click` and `telnet` :) that is missing currently.

```
buildah bud -t prom:test -f Dockerfile .
STEP 1: FROM registry.access.redhat.com/ubi8:8.2
STEP 2: USER root
STEP 3: COPY build/repos/opstools.repo /etc/yum.repos.d/opstools.repo
STEP 4: RUN dnf -y install python3-cherrypy python3-PyYAML python3-pysnmp                    python3-dateutil python3-click git                    prometheus-webhook-snmp                    python3-prometheus_client procps-ng telnet lsof && dnf clean all
Updating Subscription Management repositories.
Unable to read consumer identity
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
CentOS-8 - OpsTools - collectd                                                                                                                                                                                256 kB/s | 143 kB     00:00    
Red Hat Universal Base Image 8 (RPMs) - BaseOS                                                                                                                                                                1.9 MB/s | 771 kB     00:00    
Red Hat Universal Base Image 8 (RPMs) - AppStream                                                                                                                                                              10 MB/s | 4.8 MB     00:00    
Red Hat Universal Base Image 8 (RPMs) - CodeReady Builder                                                                                                                                                      71 kB/s |  13 kB     00:00    
Package python3-dateutil-1:2.6.1-6.el8.noarch is already installed.
No match for argument: python3-click
No match for argument: telnet
Error: Unable to find a match: python3-click telnet
error building at STEP "RUN dnf -y install python3-cherrypy python3-PyYAML python3-pysnmp                    python3-dateutil python3-click git                    prometheus-webhook-snmp                    python3-prometheus_client procps-ng telnet lsof && dnf clean all": error while running runtime: exit status 1
ERRO exit status 1                                
```

**Comment by mrunge** [comment]
python3-click is in http://mirror.centos.org/centos-8/8.3.2011/AppStream/x86_64/os/Packages/ (for example).

Telnet is not needed, it was helpful for me while debugging.

**Comment by leifmadsen** [comment]
Unfortunately this doesn't look simple at this point, especially if I'm going to be pulling in CentOS repositories. I'll take a different intermittent approach instead.

**Pull request closed without merging**
